site_name: Conversations
site_url: https://rob-luke.github.io/conversations/

theme:
  name: "material"

nav:
    - Home: index.md
    - API: api.md
    - Contributing: contributing.md
    - Changelog: changelog.md

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: numpy
