site_name: Conversations
site_url: https://rob-luke.github.io/conversations/
repo_url: https://github.com/rob-luke/conversations

theme:
  name: "material"

nav:
    - Home: index.md
    - Examples: examples.md
    - API: api.md
    - Contributing: contributing.md
    - Changelog: changelog.md

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: numpy
