site_name: Conversations
site_url: https://example.com/

theme:
  name: "material"

nav:
    - Home: index.md
    - API: api.md

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: numpy
