name: Semantic Release

on:
  push:
    branches:
      - main

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
  REPOSITORY_USERNAME: __token__

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup git user
      run: |
          git config --global user.name "rob-luke"
          git config --global user.email "code@robertluke.net"

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: Install Hatch
      run: pip install --upgrade hatch

    - name: Run release
      run: hatch run semantic-release publish -v DEBUG
