on:
  pull_request:

name: Suggestions

jobs:
  shell:

  black:
    name: Black formatter
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false

      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."

      - name: suggester / black
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: black
